### ISSUE TITLE
Add more Special Number programs in any language you know.

### ISSUE THREAD

**Issue by aryan-upa** [aryan-upa/SpecialNumberPrograms#10]
Here we are **building a resource** on which people can find programs for numbers which are usually asked in the **coding-interviews**. 

If you know how to code in any language [ C / C++ / Python / Ruby / Scala / Go / PHP / etc. ] you can come and contribute to the repository.

Know more about contribution by clicking [here](https://github.com/aryan-upa/SpecialNumberPrograms/blob/master/CONTRIBUTING.md).

Unsure of what are [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines), now you're not.

**Comment by akshaygidwani404** [comment]
Hi @aryan-upa! I can contribute in adding few special number programs. Do assign me this issue.

**Comment by aryan-upa** [comment]
Go ahead!

**Comment by mokshUpadhyay57** [comment]
Working on it.....
